Repository opf/primer_view_components, pull requests merged in 2024-07, with the labels that each got.

#137 Bump/primer upstream 0.27.0
  .changeset/forty-ways-grab.md
  .changeset/short-ligers-smile.md
  .changeset/tough-otters-sniff.md
  .github/workflows/lint.yml
  .github/workflows/release-canary.yml
  .github/workflows/release-candidate.yml
  .github/workflows/release_tracking.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/action_list/listbox/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/action_list/listbox/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/text_field/with_placeholder/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/text_field/with_placeholder/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/full_width/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/full_width/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/large/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/large/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/leading_visual/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/leading_visual/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/medium/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/medium/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/small/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/small/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/trailing_action/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/trailing_action/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/visually_hide_label/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/auto_complete/visually_hide_label/focused.png
  Gemfile.lock
  app/components/primer/alpha/action_list.rb
  app/components/primer/alpha/action_list/item.rb
  app/components/primer/alpha/action_menu.rb
  app/components/primer/focus_group.ts
  demo/Gemfile
  demo/Gemfile.lock
  demo/package-lock.json
  demo/package.json
  lib/primer/classify/utilities.rb
  package-lock.json
  package.json
  previews/primer/alpha/action_list_preview.rb
  primer_view_components.gemspec
  script/test
  static/arguments.json
  static/constants.json
  static/info_arch.json
  static/previews.json
  test/components/alpha/action_list_test.rb
  test/components/alpha/action_menu_test.rb
  test/performance/bench_utilities.rb
Labels: minor release

#140 [56060] spacing between title and tabs in page headers is too small
  .changeset/modern-otters-count.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/page_header/default/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/page_header/default/focused.png
  app/components/primer/open_project/page_header.pcss
Labels: patch release

#142 [56060] Spacing between title and tabs in page headers is too small
  .changeset/quick-papayas-exercise.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/page_header/default/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/page_header/default/focused.png
  app/components/primer/open_project/page_header.pcss
Labels: patch release

#143 chore[Op#51376]: remove wrapping flex container that is causing caption and input group to be squeezed together
  .changeset/sweet-jars-matter.md
  app/components/primer/open_project/input_group.html.erb
Labels: patch release

#138 Introduce side panel
  .changeset/brave-impalas-grab.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/side_panel/default/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/side_panel/default/focused.png
  app/components/primer/open_project/border_grid.rb
  app/components/primer/open_project/side_panel.html.erb
  app/components/primer/open_project/side_panel.rb
  app/components/primer/open_project/side_panel/section.html.erb
  app/components/primer/open_project/side_panel/section.pcss
  app/components/primer/open_project/side_panel/section.rb
  app/components/primer/primer.pcss
  demo/Gemfile.lock
  previews/primer/open_project/side_panel_preview.rb
  previews/primer/open_project/side_panel_preview/default.html.erb
  previews/primer/open_project/side_panel_preview/playground.html.erb
  previews/primer/open_project/side_panel_preview/with_component.html.erb
  static/classes.json
  test/components/component_test.rb
  test/components/primer/open_project/side_panel_test.rb
  test/system/open_project/side_panel_test.rb
Labels: minor release

#146 Fix spacings inside SidePanel::Section
  .changeset/tame-cycles-remain.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/side_panel/default/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/side_panel/default/focused.png
  app/components/primer/open_project/side_panel/section.pcss
Labels: bug, patch release

#152 Bump/primer upstream 0.29.0
  .changeset/calm-maps-wave.md
  .github/workflows/lint.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/dark.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/dark_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/dark_dimmed.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/dark_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/light.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/light_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/light_high_contrast.png
  app/components/primer/alpha/select_panel.rb
  app/components/primer/alpha/select_panel_element.ts
  demo/Gemfile.lock
  demo/app/views/select_panel_items/index.html.erb
  package-lock.json
  previews/primer/alpha/select_panel_preview/playground.html.erb
  static/arguments.json
  static/audited_at.json
  static/constants.json
  static/info_arch.json
  static/statuses.json
  test/system/alpha/select_panel_test.rb
Labels: minor release

#154 Update preview examples of PageHeader
  .changeset/twenty-poets-glow.md
  previews/primer/open_project/page_header_preview.rb
  previews/primer/open_project/page_header_preview/create_action.html.erb
Labels: patch release

#156 Bump/primer upstream 0.30.0
  .changeset/hip-glasses-wave.md
  .changeset/warm-gorillas-beg.md
  .changeset/wild-onions-explode.md
  app/components/primer/alpha/action_list.pcss
  app/components/primer/alpha/select_panel_element.ts
  app/components/primer/alpha/toggle_switch.rb
  app/components/primer/alpha/toggle_switch.ts
  previews/primer/alpha/toggle_switch_preview.rb
  static/arguments.json
  static/info_arch.json
  static/previews.json
  test/components/alpha/toggle_switch_test.rb
  test/system/alpha/select_panel_test.rb
  test/system/alpha/toggle_switch_test.rb
Labels: minor release
