Repository opf/primer_view_components, pull requests merged in 2025-06, with the labels that each got.

#318 Include routes into build gem
  .changeset/giant-pants-carry.md
  primer_view_components.gemspec
Labels: patch release

#325 enable sub menu in sub header action menu
  .changeset/fair-cloths-guess.md
  app/components/primer/open_project/sub_header/menu.rb
Labels: minor release

#328 Bump/primer upstream
  .changeset/angry-panthers-lay.md
  .github/workflows/release.yml
  .github/workflows/static-files.yml
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  demo/Gemfile
  demo/Gemfile.lock
  demo/config/application.rb
  demo/config/environments/production.rb
  demo/config/environments/test.rb
  package-lock.json
  package.json
  test/performance/bench_octicons.rb
Labels: patch release

#333 Bump/primer upstream
  .changeset/mighty-cobras-bake.md
  Gemfile
  Gemfile.lock
  app/lib/primer/experimental_slot_helpers.rb
  demo/Gemfile
  demo/Gemfile.lock
  demo/config/application.rb
Labels: patch release

#336 `script/merge-upstream` workflow fixes
  .gitattributes
  script/merge-upstream
Labels: skip changeset
