Repository opf/primer_view_components, pull requests merged in 2025-02, with the labels that each got.

#236 Fix Danger Dialog regression: unable to set custom button text
  .changeset/gold-moles-beg.md
  app/components/primer/open_project/danger_dialog.rb
  previews/primer/open_project/danger_dialog_preview/playground.html.erb
  test/components/primer/open_project/danger_dialog_test.rb
  test/system/open_project/danger_dialog_test.rb
Labels: patch release

#237 Make title param required for DangerDialog and FeedbackDialog
  .changeset/nasty-oranges-end.md
  .changeset/polite-toys-tap.md
  app/components/primer/open_project/danger_dialog.rb
  app/components/primer/open_project/feedback_dialog.rb
  previews/primer/open_project/danger_dialog_preview/with_additional_details.html.erb
  previews/primer/open_project/feedback_dialog_preview/playground.html.erb
  previews/primer/open_project/feedback_dialog_preview/with_additional_details.html.erb
  previews/primer/open_project/feedback_dialog_preview/with_custom_footer.html.erb
  static/arguments.json
  static/info_arch.json
  test/components/component_test.rb
  test/components/primer/open_project/danger_dialog_test.rb
  test/components/primer/open_project/feedback_dialog_test.rb
Labels: patch release

#239 [61293] Sub-headlines are larger than the actual PageHeader
  .changeset/early-beds-explode.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/heading/default/aria-snapshot.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/heading/default/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/heading/default/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/page_header/default/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/page_header/default/focused.png
  app/components/primer/open_project/heading.rb
  app/components/primer/open_project/page_header.pcss
  previews/primer/open_project/heading_preview.rb
  test/components/component_test.rb
  test/components/primer/open_project/heading_test.rb
  test/system/open_project/heading_test.rb
Labels: minor release

#246 [#61630] Danger Dialog should use `alertdialog` ARIA role
  .changeset/gold-clouds-explain.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_dialog/default/aria-snapshot--after-interaction.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_dialog/with_confirmation_check_box/aria-snapshot--after-interaction.yml
  app/components/primer/open_project/danger_dialog.rb
  app/components/primer/open_project/danger_dialog_form_helper.ts
  test/components/primer/open_project/danger_dialog_test.rb
Labels: patch release

#243 [#61546] Fix DangerDialog scroll behaviour w/form
  .changeset/soft-pots-return.md
  app/components/primer/open_project/danger_dialog_form_helper.ts
Labels: bug, patch release

#245 [#61347] Danger and Feedback Dialogs have broken ARIA describedby attribute value
  .changeset/polite-pets-shop.md
  .changeset/twelve-bags-dance.md
  app/components/primer/open_project/danger_dialog.rb
  app/components/primer/open_project/feedback_dialog.rb
  test/components/primer/open_project/danger_dialog_test.rb
  test/components/primer/open_project/feedback_dialog_test.rb
Labels: bug, patch release

#252 Allow ActionMenu as sidepanel section action
  .changeset/strong-months-carry.md
  app/components/primer/open_project/side_panel/section.rb
  previews/primer/open_project/side_panel_preview.rb
  previews/primer/open_project/side_panel_preview/with_action_menu.html.erb
  test/components/primer/open_project/side_panel_test.rb
Labels: minor release
