Repository opf/primer_view_components, pull requests merged in 2025-04, with the labels that each got.

#260 [62577] Create a `BorderBox::CollapsibleHeader` component
  .changeset/brown-comics-wait.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/collapsed/aria-snapshot.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/collapsed/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/collapsed/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/default/aria-snapshot.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/default/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/default/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/with_count/aria-snapshot.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/with_count/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/with_count/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/with_description/aria-snapshot.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/with_description/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/border_box/collapsible_header/with_description/focused.png
  app/components/primer/open_project/border_box/collapsible_header.html.erb
  app/components/primer/open_project/border_box/collapsible_header.pcss
  app/components/primer/open_project/border_box/collapsible_header.rb
  app/components/primer/open_project/border_box/collapsible_header.ts
  app/components/primer/primer.pcss
  app/components/primer/primer.ts
  previews/primer/open_project/border_box/collapsible_header_preview.rb
  previews/primer/open_project/border_box/collapsible_header_preview/playground.html.erb
  static/classes.json
  test/components/component_test.rb
  test/components/primer/open_project/border_box/collapsible_header_test.rb
  test/system/open_project/border_box/collapsible_header_test.rb
  test/system/test_case.rb
Labels: minor release

#263 [62747] CollapsibleHeader example not working in Lookbook
  .changeset/spotty-islands-battle.md
  app/components/primer/open_project/border_box/collapsible_header.ts
Labels: patch release

#265 Safeguard JS targets for CollapsibleHeaders
  .changeset/lazy-needles-float.md
  app/components/primer/open_project/border_box/collapsible_header.rb
  app/components/primer/open_project/border_box/collapsible_header.ts
  test/components/primer/open_project/border_box/collapsible_header_test.rb
Labels: patch release

#268 Bump/primer upstream 0.40.0
  .changeset/six-moose-wait.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/banner/scheme_upsell/aria-snapshot.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/banner/scheme_upsell/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/banner/scheme_upsell/focused.png
  app/components/primer/alpha/banner.pcss
  app/components/primer/alpha/banner.rb
  app/components/primer/alpha/select_panel.rb
  demo/Gemfile
  demo/Gemfile.lock
  demo/package-lock.json
  demo/package.json
  docs/adr/0246-record-architecture-decisions.md
  docs/adr/0250-developing-and-publishing-clientside-behaviours.md
  docs/adr/0251-use-catalyst-for-client-side-behaviours.md
  docs/adr/0252-build-component-css-with-ruby-code.md
  package-lock.json
  previews/primer/alpha/banner_preview.rb
  test/components/alpha/banner_test.rb
Labels: minor release

#267 [61779] Form input: introduce a smaller input size for date/time
  .changeset/eleven-cooks-attend.md
  app/components/primer/alpha/select.rb
  app/components/primer/alpha/text_area.rb
  app/components/primer/alpha/text_field.pcss
  app/components/primer/alpha/text_field.rb
  app/components/primer/open_project/input_group.pcss
  app/components/primer/open_project/input_group.rb
  app/lib/primer/forms/dsl/input.rb
  previews/primer/alpha/select_preview.rb
  previews/primer/alpha/text_area_preview.rb
  previews/primer/alpha/text_field_preview.rb
  previews/primer/forms_preview/custom_width_fields_form.html.erb
  previews/primer/open_project/input_group_preview.rb
  test/css/component_specific_selectors_test.rb
  test/lib/primer/forms_test.rb
Labels: patch release

#271 [#63270] Update CollapsibleHeader to use slots for greater flexibility
  .changeset/hungry-terms-attend.md
  app/components/primer/open_project/border_box/collapsible_header.html.erb
  app/components/primer/open_project/border_box/collapsible_header.rb
  previews/primer/open_project/border_box/collapsible_header_preview/playground.html.erb
  test/components/component_test.rb
  test/components/primer/open_project/border_box/collapsible_header_test.rb
Labels: minor release

#275 [634442] Missing space when putting multiple CollapsibleSections below each other
  .changeset/sad-planes-think.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/collapsible_section/collapsed/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/collapsible_section/collapsed/focused.png
  app/components/primer/open_project/collapsible_section.html.erb
Labels: bug, patch release

#276 [63443] Collapsed preview not working
  .changeset/petite-ties-repair.md
  app/components/primer/open_project/border_box/collapsible_header.html.erb
  app/components/primer/open_project/border_box/collapsible_header.rb
  app/components/primer/open_project/collapsible.ts
  app/components/primer/open_project/collapsible_section.html.erb
Labels: bug, patch release

#279 Bump/primer upstream 0.41.0
  .changeset/friendly-swans-invite.md
  .changeset/popular-eggs-notice.md
  .github/workflows/add-to-inbox.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  Gemfile
  Gemfile.lock
  demo/Gemfile.lock
  demo/config/application.rb
  demo/config/environments/test.rb
  demo/kuby.rb
  demo/package-lock.json
  demo/package.json
  package-lock.json
  package.json
  previews/primer/open_project/page_header_preview.rb
  previews/primer/open_project/page_header_preview/playground.html.erb
  primer_view_components.gemspec
  test/system/alpha/text_field_test.rb
Labels: minor release

#281 Bump/primer upstream 0.42.0
  .changeset/odd-planes-stop.md
  .changeset/pink-items-stand.md
  Gemfile
  Gemfile.lock
  app/components/primer/alpha/action_menu.html.erb
  app/components/primer/alpha/include_fragment.rb
  app/components/primer/alpha/select_panel.html.erb
  app/components/primer/conditional_wrapper.rb
  demo/app/controllers/include_fragment_controller.rb
  demo/app/views/include_fragment/deferred.html.erb
  demo/config/routes.rb
  lib/primer/view_components/linters/argument_mappers/include_fragment.rb
  lib/primer/view_components/linters/include_fragment_component_migration_counter.rb
  package-lock.json
  package.json
  previews/primer/alpha/include_fragment_preview.rb
  test/components/component_test.rb
  test/components/conditional_wrapper_test.rb
  test/components/primer/alpha/include_fragment_test.rb
  test/lib/erblint/include_fragment_component_migration_counter_test.rb
Labels: minor release

#284 Bump/primer upstream 0.43.0
  .changeset/hip-cherries-glow.md
  .changeset/modern-cheetahs-thank.md
  .changeset/sour-beds-draw.md
  .github/workflows/lint.yml
  Gemfile
  Gemfile.lock
  app/components/primer/alpha/dialog/header.html.erb
  app/components/primer/alpha/dialog/header.rb
  app/components/primer/alpha/include_fragment.rb
  app/components/primer/alpha/select_panel.html.erb
  app/lib/primer/current_attributes.rb
  demo/Gemfile.lock
  demo/package-lock.json
  demo/package.json
  docs/adr/0246-record-architecture-decisions.md
  docs/adr/0250-developing-and-publishing-clientside-behaviours.md
  docs/adr/0251-use-catalyst-for-client-side-behaviours.md
  docs/adr/0252-build-component-css-with-ruby-code.md
  package-lock.json
  previews/primer/alpha/dialog_preview.rb
  previews/primer/alpha/dialog_preview/with_header_close_button_label.html.erb
  previews/primer/alpha/dialog_preview/without_header_close_button_label.html.erb
  previews/primer/open_project/page_header_preview/playground.html.erb
  previews/primer/open_project/sub_header_preview/action_menu_buttons.html.erb
  primer_view_components.gemspec
  test/components/primer/alpha/dialog_test.rb
  test/components/primer/alpha/include_fragment_test.rb
  test/components/primer/open_project/page_header_test.rb
Labels: patch release

#286 [61631] Primer Dialog close button ARIA label is not localised
  .changeset/upset-boats-smoke.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_dialog/default/aria-snapshot--after-interaction.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_dialog/with_confirmation_check_box/aria-snapshot--after-interaction.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/feedback_dialog/default/aria-snapshot--after-interaction.yml
  app/components/primer/open_project/danger_dialog.html.erb
  app/components/primer/open_project/feedback_dialog.html.erb
Labels: bug, patch release
