Repository opf/primer_view_components, pull requests merged in 2025-01, with the labels that each got.

#219 [#60359] Harmonise FeedbackDialog slot naming
  .changeset/short-students-type.md
  app/components/primer/open_project/feedback_dialog.html.erb
  app/components/primer/open_project/feedback_dialog.rb
  previews/primer/open_project/danger_confirmation_dialog_preview/playground.html.erb
  previews/primer/open_project/feedback_dialog_preview.rb
  previews/primer/open_project/feedback_dialog_preview/playground.html.erb
  previews/primer/open_project/feedback_dialog_preview/with_additional_details.html.erb
  previews/primer/open_project/feedback_dialog_preview/with_custom_footer.html.erb
  static/info_arch.json
  static/previews.json
  test/components/primer/open_project/feedback_dialog_test.rb
Labels: minor release

#224 FIx `DangerConfirmationDialog` internal components status
  app/components/primer/open_project/danger_confirmation_dialog/confirmation_check_box.rb
  app/components/primer/open_project/danger_confirmation_dialog/form_wrapper.rb
  static/arguments.json
  static/audited_at.json
  static/constants.json
  static/form_previews.json
  static/info_arch.json
  static/previews.json
  static/statuses.json
Labels: skip changeset

#225 Button to dismiss Danger Dialog should read Cancel
  .changeset/slow-pans-applaud.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_confirmation_dialog/default/dark.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_confirmation_dialog/default/dark_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_confirmation_dialog/default/dark_dimmed.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_confirmation_dialog/default/dark_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_confirmation_dialog/default/light.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_confirmation_dialog/default/light_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/danger_confirmation_dialog/default/light_high_contrast.png
  app/components/primer/open_project/danger_confirmation_dialog.html.erb
Labels: patch release

#223 `FeedbackDialog` and `DangerConfirmationDialog` yardoc improvements
  app/components/primer/open_project/danger_confirmation_dialog.rb
  app/components/primer/open_project/feedback_dialog.rb
  static/arguments.json
  static/info_arch.json
Labels: skip changeset

#229 Bump/primer upstream 0.36.5
  .changeset/poor-parrots-fold.md
  .github/workflows/test.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/button/invisible_all_visuals/aria-snapshot.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/button/trailing_counter/aria-snapshot.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/beta/button/trailing_visual/aria-snapshot.yml
  app/components/primer/beta/button.html.erb
  app/components/primer/beta/button.rb
  demo/kuby.rb
  package-lock.json
  previews/primer/alpha/tooltip_preview.rb
  static/arguments.json
  static/info_arch.json
Labels: patch release

#232 Custom texts for Buttons in DangerConfirmationDialog
  .changeset/itchy-lions-count.md
  app/components/primer/open_project/danger_confirmation_dialog.html.erb
  app/components/primer/open_project/danger_confirmation_dialog.rb
  previews/primer/open_project/danger_confirmation_dialog_preview.rb
  previews/primer/open_project/danger_confirmation_dialog_preview/playground.html.erb
Labels: patch release
