Repository opf/primer_view_components, pull requests merged in 2025-05, with the labels that each got.

#291 Bump/primer upstream 0.43.1
  .changeset/hungry-doors-occur.md
  .changeset/tall-windows-dress.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/eventually_local_fetch_no_results/dark.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/eventually_local_fetch_no_results/dark_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/eventually_local_fetch_no_results/dark_dimmed.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/eventually_local_fetch_no_results/dark_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/eventually_local_fetch_no_results/light.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/eventually_local_fetch_no_results/light_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/eventually_local_fetch_no_results/light_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/dark.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/dark_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/dark_dimmed.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/dark_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/light.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/light_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/local_fetch_no_results/light_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/remote_fetch_no_results/dark.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/remote_fetch_no_results/dark_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/remote_fetch_no_results/dark_dimmed.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/remote_fetch_no_results/dark_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/remote_fetch_no_results/light.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/remote_fetch_no_results/light_colorblind.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/alpha/select_panel/remote_fetch_no_results/light_high_contrast.png
  app/components/primer/alpha/select_panel.html.erb
  app/components/primer/alpha/select_panel.pcss
  app/lib/primer/forms/acts_as_component.rb
  demo/package-lock.json
  demo/package.json
  test/css/component_selector_use_test.rb
Labels: patch release

#293 Revert "Version Packages"
  .changeset/four-worms-melt.md
  .changeset/hungry-doors-occur.md
  .changeset/tall-windows-dress.md
  CHANGELOG.md
  Gemfile.lock
  demo/Gemfile.lock
  lib/primer/view_components/version.rb
  package-lock.json
  package.json
Labels: minor release

#296 Fix flickering TreeView test
  test/system/open_project/tree_view_test.rb
Labels: skip changeset

#297 Skip CSS use test for `TreeView`'s playground preview
  test/css/component_selector_use_test.rb
Labels: skip changeset

#295 Revert "Version Packages"
  .changeset/four-worms-melt.md
  .changeset/hungry-doors-occur.md
  .changeset/tall-windows-dress.md
  CHANGELOG.md
  Gemfile.lock
  demo/Gemfile.lock
  lib/primer/view_components/version.rb
  package-lock.json
  package.json
Labels: minor release

#292 [60332] Implement proper mobile behaviour for Sub Header component (OP Primer)
  .changeset/fuzzy-ravens-speak.md
  app/components/primer/open_project/page_header.rb
  app/components/primer/open_project/sub_header.html.erb
  app/components/primer/open_project/sub_header.pcss
  app/components/primer/open_project/sub_header.rb
  app/components/primer/open_project/sub_header/button.rb
  app/components/primer/open_project/sub_header/button_group.rb
  app/components/primer/open_project/sub_header/menu.rb
  app/components/primer/open_project/sub_header/segmented_control.rb
  previews/primer/open_project/page_header_preview/create_action.html.erb
  previews/primer/open_project/sub_header_preview.rb
  previews/primer/open_project/sub_header_preview/action_menu_buttons.html.erb
  previews/primer/open_project/sub_header_preview/button_group.html.erb
  previews/primer/open_project/sub_header_preview/custom_filter_button.html.erb
  previews/primer/open_project/sub_header_preview/dialog_buttons.html.erb
  static/classes.json
  test/components/component_test.rb
  test/components/primer/open_project/sub_header/button_group_test.rb
  test/components/primer/open_project/sub_header/button_test.rb
  test/components/primer/open_project/sub_header/menu_test.rb
  test/components/primer/open_project/sub_header/segemented_control_test.rb
  test/components/primer/open_project/sub_header_test.rb
  test/css/component_specific_selectors_test.rb
Labels: minor release

#301 [Bug] Space for filter button
  .changeset/silver-tables-hope.md
  app/components/primer/open_project/sub_header.rb
Labels: patch release

#303 [#63920] Fix issue causing TreeView sub-trees to not expand/collapse when clicking the arrows
  .changeset/upset-pets-rest.md
  app/components/primer/open_project/tree_view/tree_view_sub_tree_node_element.ts
Labels: patch release

#306 [64149] Raise an error if no string is passed to the CollapsibleSection
  .changeset/thin-jeans-help.md
  app/components/primer/open_project/border_box/collapsible_header.rb
  app/components/primer/open_project/collapsible_section.rb
  previews/primer/open_project/border_box/collapsible_header_preview/playground.html.erb
  test/components/primer/open_project/border_box/collapsible_header_test.rb
  test/components/primer/open_project/collapsible_section_test.rb
Labels: patch release

#305 [#64132] Allow `TreeView` nodes to be anchors or buttons
  .changeset/heavy-buses-bet.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/file_tree_view/default/aria-snapshot--after-interaction.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/file_tree_view/default/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/file_tree_view/default/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/file_tree_view/default/light_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/default/aria-snapshot--after-interaction.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/default/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/default/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/default/light_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/empty/aria-snapshot--after-interaction.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/empty/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/empty/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/empty/light_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_failure/aria-snapshot--after-interaction.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_failure/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_failure/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_failure/light_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_skeleton/aria-snapshot--after-interaction.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_skeleton/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_skeleton/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_skeleton/light_high_contrast.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_spinner/aria-snapshot--after-interaction.yml
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_spinner/default.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_spinner/focused.png
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/tree_view/loading_spinner/light_high_contrast.png
  app/components/primer/open_project/tree_view.pcss
  app/components/primer/open_project/tree_view.rb
  app/components/primer/open_project/tree_view/node.html.erb
  app/components/primer/open_project/tree_view/node.rb
  app/components/primer/open_project/tree_view/skeleton_loader.html.erb
  app/components/primer/open_project/tree_view/spinner_loader.html.erb
  app/components/primer/open_project/tree_view/sub_tree.html.erb
  app/components/primer/open_project/tree_view/sub_tree.rb
  app/components/primer/open_project/tree_view/sub_tree_node.rb
  app/components/primer/open_project/tree_view/tree_view.ts
  app/components/primer/open_project/tree_view/tree_view_roving_tab_index.ts
  app/components/primer/open_project/tree_view/tree_view_sub_tree_node_element.ts
  demo/app/views/tree_view_items/index.html_fragment.erb
  previews/primer/open_project/tree_view_preview.rb
  previews/primer/open_project/tree_view_preview/buttons.html.erb
  previews/primer/open_project/tree_view_preview/links.html.erb
  test/components/primer/open_project/file_tree_view_test.rb
  test/components/primer/open_project/tree_view_test.rb
  test/system/open_project/tree_view_test.rb
Labels: minor release

#308 [#64215] TreeView: Bubble expanded state from children to parents
  .changeset/sixty-horses-throw.md
  app/components/primer/open_project/tree_view/tree_view.ts
  app/components/primer/open_project/tree_view/tree_view_sub_tree_node_element.ts
  demo/app/controllers/tree_view_items_controller.rb
  demo/app/views/tree_view_items/async_alpha.html_fragment.erb
  demo/app/views/tree_view_items/index.html_fragment.erb
  demo/config/routes.rb
  previews/primer/open_project/tree_view_preview.rb
  previews/primer/open_project/tree_view_preview/async_alpha.html.erb
  test/system/open_project/tree_view_test.rb
Labels: minor release

#311 [64228] Home screen widgets have the wrong headline tag
  .changeset/good-snails-decide.md
  .playwright/screenshots/snapshots.test.ts-snapshots/primer/open_project/page_header/default/aria-snapshot.yml
  app/components/primer/open_project/page_header/title.rb
Labels: bug, patch release
